<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>VietLandHR</AssemblyName>
    <RootNamespace>VietLandHR</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.2.0" />
    <PackageReference Include="ClosedXML" Version="0.102.2" />
    <PackageReference Include="Guna.UI2.WinForms" Version="2.0.4.8" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.WinForms" Version="2.0.5" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Supabase" Version="1.1.1" />
  </ItemGroup>

</Project>